### PR TITLE
update including parallel implementation

### PR DESCRIPTION
**Pull request by tiiiecherle**
hey, this is the biggest update since the last one I contributed ;)

As I´m having a lot of brew formulas and casks installed the script took very long. While searching I found parallel and after a few struggles of implementing it, it worked fine for the last past weeks.

And the script is a lost faster than before. Perhaps I´ll have a look at parallel updating some time, but this is more than ok for me for now ;)

If you like an easier starting and app icon matching homebrew have a look here:
[https://github.com/tiiiecherle/osx_install_config/tree/master/05_homebrew_and_casks/5c_brew_casks_update](https://github.com/tiiiecherle/osx_install_config/tree/master/05_homebrew_and_casks/5c_brew_casks_update)

Hope you like the changes ;)

Have a nice weekend

### CODE REVIEW

**Comment by derrekyoung** [comment]
This is awesome. I see that it checks for jq and parallel.

What do I need to do to get your DMG version running?

**Comment by derrekyoung** [comment]
@tiiiecherle, this is awesome. I see that it checks for jq and parallel.

What do I need to do to get your DMG version running?

**Comment by tiiiecherle** [comment]
hey, glad you like it ;)

just head over to 
[https://github.com/tiiiecherle/osx_install_config](https://github.com/tiiiecherle/osx_install_config)
and press the green "clone or download" button and download as zip.

unarchive the zip, inside the unarchived files navigate to 
/osx_install_config-master/05_homebrew_and_casks/5c_brew_casks_update/brew_casks_update.dmg

open the dmg and double click the
run_to_install.command
file.

this will install
brew_casks_update.app
including the script to your /Applications folder.

Just double click the app in the applications folder to run the script.

Let me know if it`s working.

Kind regards

**Comment by tiiiecherle** [comment]
as I just saw it on the first page of your github, I never payed attention to excluding casks and therefore I think this will no longer work
`./brew-cask-upgrade.sh "<BREW_EXCLUDES>" "<CASK_EXCLUDES>"`
but I actually haven't tried and don`t know.

**Pull request merged**
