### PR TITLE
a few updates and improvements over the last months ;)

### PR DESCRIPTION
**Pull request by tiiiecherle**

### CODE REVIEW

**Comment by derrekyoung** [comment]
Hey, thanks for keeping this up. I haven't had a chance to contribute, but I do still use the script. Thanks!

**Comment by derrekyoung** [comment]
See previous comment

**Comment by tiiiecherle** [comment]
Hey, sure. We use it a lot in the office.

I did a big code cleanup and rewrite the last days. I will give you a pull request asap ;)

**Comment by tiiiecherle** [comment]
done ;)))

**Pull request merged**
