### PR TITLE
big update

### PR DESCRIPTION
**Pull request by tiiiecherle**
Hey,

thanks for the very nice script.

I tried to make it even better and it is working for me so far.

Kind regards

### CODE REVIEW

**Comment by derrekyoung** [comment]
tiiiecherle,

Wow, lots of stuff in here. Thanks for the contribution. Would you mind breaking down your additions so I can more easily understand the steps?

Thanks

**Comment by tiiiecherle** [comment]
Hey Derrek,

I actually did further improvements after the pull request ;)

You can find the current version here:
[https://github.com/tiiiecherle/osx_install_config/blob/master/05_homebrew_and_casks/5c_brew_casks_update/bash/brew_casks_update.sh](url)

Here a short summary of what I changed / added:

1 asking for the password upfront and only once (first part of the script)
I did put a lot of research in this to make it safe/secure. You type the password and use it for formulas installs and even for sudo (casks) installs. It never leaves the script, only uses bash builtin commands and does not show in the output os ps.

2 colored output
I added green for true and red for false ;)

3 install only at end of block
I did not want to install the app directly after the check but wait for the homebrew or casks block to finish checking. during the check all entries that end with "false" are written to a local temp file. After each block all entries from this block are updated.

4 "latest" version option
A few casks are taged with latest instead of the version number. I added an option to say yes or no to update them. In my current version it is disabled. Just uncomment the line with the PS3 entry and comment the line below to activate it like this
`read -p 'do you want to update all installed casks that show "latest" as version (y/N)? ' CONT_LATEST
#CONT_LATEST="N"`

5 run as .app
as I want to run this script easily I created an app with icon that you only double click, then a terminal starts and runs the script. you can find it here:
[https://github.com/tiiiecherle/osx_install_config/tree/master/05_homebrew_and_casks/5c_brew_casks_update](url)
when you download the github repository go to this folder, open the .dmg and right click on the "run to install" script (to make gatekeeper allow the install). this should copy the app to the /Applications folder and adjust the permissions. Should be easy to run by opening the app.

Hope that helps ;)

Thanks again for the very good start of the script ;)

If you are interested number 5b in my scripts is my hombrew and cask install script. I´m happy for any feedback.

**Comment by tiiiecherle** [comment]
Hey Derrek,

I actually did further improvements after the pull request ;)

You can find the current version here:
[https://github.com/tiiiecherle/osx_install_config/blob/master/05_homebrew_and_casks/5c_brew_casks_update/bash/brew_casks_update.sh](https://github.com/tiiiecherle/osx_install_config/blob/master/05_homebrew_and_casks/5c_brew_casks_update/bash/brew_casks_update.sh)

Here a short summary of what I changed / added:

1 asking for the password upfront and only once (first part of the script)
I did put a lot of research in this to make it safe/secure. You type the password and use it for formulas installs and even for sudo (casks) installs. It never leaves the script, only uses bash builtin commands and does not show in the output os ps.

2 colored output
I added green for true and red for false ;)

3 install only at end of block
I did not want to install the app directly after the check but wait for the homebrew or casks block to finish checking. during the check all entries that end with "false" are written to a local temp file. After each block all entries from this block are updated.

4 "latest" entries option
A few casks are taged with latest instead of the version number. I added an option to say yes or no to update them. In my current version it is disabled. Just uncomment the line with the PS3 entry and comment the line below to activate it like this
`read -p 'do you want to update all installed casks that show "latest" as version (y/N)? ' CONT_LATEST
#CONT_LATEST="N"`

5 run as .app
as I want to run this script easily I created an app with icon that you only double click, then a terminal starts and runs the script. you can find it here:
[https://github.com/tiiiecherle/osx_install_config/tree/master/05_homebrew_and_casks/5c_brew_casks_update](https://github.com/tiiiecherle/osx_install_config/tree/master/05_homebrew_and_casks/5c_brew_casks_update)
when you download the github repository go to this folder, open the .dmg and right click on the "run to install" script (to make gatekeeper allow the install). this should copy the app to the /Applications folder and adjust the permissions. Should be easy to run by opening the app.

6 checking for command line tools at the start of the script

7 a few minor and output changes

Hope that helps ;)

Thanks again for the very good start of the script ;)

If you are interested number 5b in my scripts is my homebrew and casks install script. I´m happy for any feedback.

**Comment by derrekyoung** [comment]
Wow, you're on fire. Thanks so much for contributing.

**Comment by tiiiecherle** [comment]
you`re welcome. I tried to adjust the script each time something came up during the updates that was not working. looks pretty good for now ;)

I´ll keep updating when anything comes up. If you find anything just let me know.

Have you tried the "script-app-wrapper" I built as described in point 5 above? I use it everytime I use this script and it`s working nicely...

thanks again for the very good start of the script ;)

**Pull request merged**
